package message

// ReceiveIDType 接收者 ID 类型
type ReceiveIDType string

const (
	ReceiveIDTypeOpenID  ReceiveIDType = "open_id"
	ReceiveIDTypeUserID  ReceiveIDType = "user_id"
	ReceiveIDTypeUnionID ReceiveIDType = "union_id"
	ReceiveIDTypeEmail   ReceiveIDType = "email"
	ReceiveIDTypeChatID  ReceiveIDType = "chat_id"
)

// ImageType 图片类型
type ImageType string

const (
	ImageTypeMessage ImageType = "message"
	ImageTypeAvatar  ImageType = "avatar"
)

// FileType 文件类型
type FileType string

const (
	FileTypeOpus   FileType = "opus"
	FileTypeMp4    FileType = "mp4"
	FileTypePdf    FileType = "pdf"
	FileTypeDoc    FileType = "doc"
	FileTypeXls    FileType = "xls"
	FileTypeStream FileType = "stream"
)

// EmojiType 表情类型
type EmojiType string

const (
	EmojiThumbsUp     EmojiType = "THUMBSUP"
	EmojiOK           EmojiType = "OK"
	EmojiThanks       EmojiType = "THANKS"
	EmojiMuscle       EmojiType = "MUSCLE"
	EmojiFingerHeart  EmojiType = "FINGERHEART"
	EmojiApplause     EmojiType = "APPLAUSE"
	EmojiFistBump     EmojiType = "FISTBUMP"
	EmojiJiaYou       EmojiType = "JIAYOU"
	EmojiOne          EmojiType = "ONE"
	EmojiSmile        EmojiType = "SMILE"
	EmojiBlush        EmojiType = "BLUSH"
	EmojiLaugh        EmojiType = "LAUGH"
	EmojiSmirk        EmojiType = "SMIRK"
	EmojiLOL           EmojiType = "LOL"
	EmojiFacePalm      EmojiType = "FACEPALM"
	EmojiLove          EmojiType = "LOVE"
	EmojiWink          EmojiType = "WINK"
	EmojiProud         EmojiType = "PROUD"
	EmojiWitty         EmojiType = "WITTY"
	EmojiSmart         EmojiType = "SMART"
	EmojiScowl         EmojiType = "SCOWL"
	EmojiThinking      EmojiType = "THINKING"
	EmojiSob           EmojiType = "SOB"
	EmojiCry           EmojiType = "CRY"
	EmojiError         EmojiType = "ERROR"
	EmojiNosePick      EmojiType = "NOSEPICK"
	EmojiHaughty      EmojiType = "HAUGHTY"
	EmojiSlap          EmojiType = "SLAP"
	EmojiSpit          EmojiType = "SPIT"
	EmojiBlood         EmojiType = "BLOOD"
	EmojiToasted       EmojiType = "TOASTED"
	EmojiGlance        EmojiType = "GLANCE"
	EmojiDull          EmojiType = "DULL"
	EmojiInnocent      EmojiType = "INNOCENT"
	EmojiSmileJoyful   EmojiType = "SMILEJOYFUL"
	EmojiWow           EmojiType = "WOW"
	EmojiTricky        EmojiType = "TRICKY"
	EmojiYeah          EmojiType = "YEAH"
	EmojiEnough        EmojiType = "ENOUGH"
	EmojiTears         EmojiType = "TEARS"
	EmojiEmbarrassed   EmojiType = "EMBARRASSED"
	EmojiKiss          EmojiType = "KISS"
	EmojiSmooch        EmojiType = "SMOOCH"
	EmojiDrool         EmojiType = "DROOL"
	EmojiObsessed      EmojiType = "OBSESSED"
	EmojiMoney         EmojiType = "MONEY"
	EmojiTease         EmojiType = "TEASE"
	EmojiShowOff       EmojiType = "SHOWOFF"
	EmojiComfort       EmojiType = "COMFORT"
	EmojiClap          EmojiType = "CLAP"
	EmojiPraise        EmojiType = "PRAISE"
	EmojiStrive        EmojiType = "STRIVE"
	EmojiX             EmojiType = "X"
	EmojiBlushSilent   EmojiType = "BLUSHSILENT"
	EmojiWave          EmojiType = "WAVE"
	EmojiWhat          EmojiType = "WHAT"
	EmojiFrown         EmojiType = "FROWN"
	EmojiShy           EmojiType = "SHY"
	EmojiDizzy         EmojiType = "DIZZY"
	EmojiLookDown      EmojiType = "LOOKDOWN"
	EmojiChuckle       EmojiType = "CHUCKLE"
	EmojiWail          EmojiType = "WAIL"
	EmojiCrazy         EmojiType = "CRAZY"
	EmojiWhimper       EmojiType = "WHIMPER"
	EmojiHug           EmojiType = "HUG"
	EmojiBlubber       EmojiType = "BLUBBER"
	EmojiWronged       EmojiType = "WRONGED"
	EmojiHusky         EmojiType = "HUSKY"
	EmojiShhh          EmojiType = "SHHH"
	EmojiSmug          EmojiType = "SMUG"
	EmojiAngry         EmojiType = "ANGRY"
	EmojiHammer        EmojiType = "HAMMER"
	EmojiShocked       EmojiType = "SHOCKED"
	EmojiTerror        EmojiType = "TERROR"
	EmojiPetrified     EmojiType = "PETRIFIED"
	EmojiSkull         EmojiType = "SKULL"
	EmojiSweat         EmojiType = "SWEAT"
	EmojiSpeechless    EmojiType = "SPEECHLESS"
	EmojiSleep         EmojiType = "SLEEP"
	EmojiDrowsy        EmojiType = "DROWSY"
	EmojiYawn          EmojiType = "YAWN"
	EmojiSick          EmojiType = "SICK"
	EmojiPuke          EmojiType = "PUKE"
	EmojiBetrayed      EmojiType = "BETRAYED"
	EmojiHeadsEte      EmojiType = "HEADS_ETE"
	EmojiEatingFood    EmojiType = "EATING_FOOD"
	EmojiMeMeMe        EmojiType = "ME_ME_ME"
	EmojiSigh          EmojiType = "SIGH"
	EmojiTyping        EmojiType = "TYPING"
	EmojiLemon         EmojiType = "LEMON"
	EmojiGet           EmojiType = "GET"
	EmojiLGTM          EmojiType = "LGTM"
	EmojiOnIt          EmojiType = "ON_IT"
	EmojiOneSecond     EmojiType = "ONE_SECOND"
	EmojiVRHeadset     EmojiType = "VR_HEADSET"
	EmojiYouAreTheBest EmojiType = "YOU_ARE_THE_BEST"
	EmojiSalute        EmojiType = "SALUTE"
	EmojiShake         EmojiType = "SHAKE"
	EmojiHighFive      EmojiType = "HIGH_FIVE"
	EmojiUpperLeft     EmojiType = "UPPER_LEFT"
	EmojiThumbsDown    EmojiType = "THUMBSDOWN"
	EmojiSlight        EmojiType = "SLIGHT"
	EmojiTongue        EmojiType = "TONGUE"
	EmojiEyesClosed    EmojiType = "EYES_CLOSED"
	EmojiRoarForYou    EmojiType = "ROAR_FOR_YOU"
	EmojiCalf          EmojiType = "CALF"
	EmojiBear          EmojiType = "BEAR"
	EmojiBull          EmojiType = "BULL"
	EmojiRainbow       EmojiType = "RAINBOW"
	EmojiPukeRose      EmojiType = "PUKE_ROSE"
	EmojiHeartParty    EmojiType = "HEART_PARTY"
	EmojiLips          EmojiType = "LIPS"
	EmojiBeer          EmojiType = "BEER"
	EmojiCake          EmojiType = "CAKE"
	EmojiGift          EmojiType = "GIFT"
	EmojiCucumber      EmojiType = "CUCUMBER"
	EmojiDrumstick     EmojiType = "DRUMSTICK"
	EmojiPepper        EmojiType = "PEPPER"
	EmojiCandiedHaws   EmojiType = "CANDIED_HAWS"
	EmojiBubbleTea     EmojiType = "BUBBLE_TEA"
	EmojiCoffee        EmojiType = "COFFEE"
	EmojiYesNoOKR      EmojiType = "YES_NO_OKR"
	EmojiCheckMark     EmojiType = "CHECK_MARK"
	EmojiCrossMark     EmojiType = "CROSS_MARK"
	EmojiMinusOneHundred EmojiType = "MINUS_ONE_HUNDRED"
	EmojiAwesome       EmojiType = "AWESOMEN"
	EmojiPin           EmojiType = "PIN"
	EmojiAlarm         EmojiType = "ALARM"
	EmojiLoudspeaker   EmojiType = "LOUDSPEAKER"
	EmojiTrophy        EmojiType = "TROPHY"
	EmojiFire          EmojiType = "FIRE"
	EmojiBomb          EmojiType = "BOMB"
	EmojiMusic         EmojiType = "MUSIC"
	EmojiXmasTree      EmojiType = "XMAS_TREE"
	EmojiSnowman       EmojiType = "SNOWMAN"
	EmojiXmasHat       EmojiType = "XMAS_HAT"
	EmojiFireworks     EmojiType = "FIREWORKS"
	EmojiRedPacket     EmojiType = "RED_PACKET"
	EmojiFortune       EmojiType = "FORTUNE"
	EmojiLuck          EmojiType = "LUCK"
	EmojiFireCrackers  EmojiType = "FIRE_CRACKERS"
	EmojiStickyRiceBalls EmojiType = "STICKY_RICE_BALLS"
	EmojiHeartBroken   EmojiType = "HEARTBROKEN"
	EmojiPoop          EmojiType = "POOP"
	EmojiFlashOfInspiration EmojiType = "FLASH_OF_INSPIRATION"
	EmojiEighteenX     EmojiType = "EIGHTEEN_X"
	EmojiCleaver       EmojiType = "CLEAVER"
	EmojiSoccer        EmojiType = "SOCCER"
	EmojiBasketball    EmojiType = "BASKETBALL"
	EmojiDoNotDisturb  EmojiType = "DO_NOT_DISTURB"
	EmojiStatusPrivateMessage EmojiType = "STATUS_PRIVATE_MESSAGE"
	EmojiStatusInMeeting EmojiType = "STATUS_IN_MEETING"
	EmojiStatusBusy    EmojiType = "STATUS_BUSY"
	EmojiStatusReading EmojiType = "STATUS_READING"
	EmojiStatusInFlight EmojiType = "STATUS_IN_FLIGHT"
	EmojiStatusBusinessTrip EmojiType = "STATUS_BUSINESS_TRIP"
	EmojiStatusWorkFromHome EmojiType = "STATUS_WORK_FROM_HOME"
	EmojiStatusEnjoyLife EmojiType = "STATUS_ENJOY_LIFE"
	EmojiStatusTravelling EmojiType = "STATUS_TRAVELLING"
	EmojiStatusCar     EmojiType = "STATUS_CAR"
	EmojiStatusBus     EmojiType = "STATUS_BUS"
	EmojiStatusSun     EmojiType = "STATUS_SUN"
	EmojiStatusMoon    EmojiType = "STATUS_MOON"
	EmojiStatusRest    EmojiType = "STATUS_REST"
	EmojiStatusMoonRabbit EmojiType = "STATUS_MOON_RABBIT"
	EmojiStatusMooncake EmojiType = "STATUS_MOONCAKE"
	EmojiStatusJubilant EmojiType = "STATUS_JUBILANT"
	EmojiStatusRabbit  EmojiType = "STATUS_RABBIT"
	EmojiStatusTV      EmojiType = "STATUS_TV"
	EmojiStatusMovie   EmojiType = "STATUS_MOVIE"
	EmojiStatusPumpkin EmojiType = "STATUS_PUMPKIN"
	EmojiStatusBeamingFace EmojiType = "STATUS_BEAMING_FACE"
	EmojiStatusDelighted EmojiType = "STATUS_DELIGHTED"
	EmojiStatusColdSweat EmojiType = "STATUS_COLD_SWEAT"
	EmojiStatusFullMoonFace EmojiType = "STATUS_FULL_MOON_FACE"
	EmojiStatusPartying EmojiType = "STATUS_PARTYING"
	EmojiStatusGoGoGo  EmojiType = "STATUS_GO_GO_GO"
	EmojiStatusThanksFace EmojiType = "STATUS_THANKS_FACE"
	EmojiStatusSaluteFace EmojiType = "STATUS_SALUTE_FACE"
	EmojiStatusShrug   EmojiType = "STATUS_SHRUG"
	EmojiStatusClownFace EmojiType = "STATUS_CLOWN_FACE"
	EmojiStatusHappyDragon EmojiType = "STATUS_HAPPY_DRAGON"
)

// MessageType 消息类型
type MessageType string

const (
	MessageTypeText         MessageType = "text"
	MessageTypePost         MessageType = "post"
	MessageTypeImage        MessageType = "image"
	MessageTypeFile         MessageType = "file"
	MessageTypeFolder       MessageType = "folder"
	MessageTypeAudio        MessageType = "audio"
	MessageTypeMedia        MessageType = "media"
	MessageTypeSticker      MessageType = "sticker"
	MessageTypeInteractive  MessageType = "interactive"
	MessageTypeRedPacket    MessageType = "red_packet"
	MessageTypeCalendar     MessageType = "calendar"
	MessageTypeShareChat    MessageType = "share_chat"
	MessageTypeShareUser    MessageType = "share_user"
	MessageTypeSystem       MessageType = "system"
	MessageTypeLocation     MessageType = "location"
	MessageTypeVideoChat    MessageType = "video_chat"
	MessageTypeTodo         MessageType = "todo"
	MessageTypeVote         MessageType = "vote"
	MessageTypeMergeForward MessageType = "merge_forward"
)

// TextStyle 文本样式类型
type TextStyle string

const (
	TextStyleBold         TextStyle = "bold"
	TextStyleItalic       TextStyle = "italic"
	TextStyleUnderline    TextStyle = "underline"
	TextStyleLineThrough  TextStyle = "lineThrough"
)
